### ISSUE TITLE
Unknown start of token

### ISSUE THREAD

**Issue by leopku** [crazywolf132/ultimate-gojust#1]
macOS 11.7.10
go v1.23.3
GNU Make 3.81
just 1.36.0

```
error: Unknown start of token:
   ——▶ justfile:147:8
    │
147 │     fmt.Println("Hello, World!")
    │        ^
```

**Comment by leopku** [comment]
PS: an exist project without `just init`.

**Comment by notxorand** [comment]
hey @leopku, have you been able to find a fix

**Comment by binbandit** [comment]
This should now be fully addressed. Please let me know if i can go ahead and close this ticket.
Thank you @leopku

**Comment by leopku** [comment]
Fixed.
Thanks.
